$('#turno1').on('click',()=>{
    location.href='turno1.html'
})
$('#regDocente').on('click',()=>{
    location.href='regDocente.html'
})
$('#btnReservas').on('click',()=>{
    location.href='reservas.html'
})